version: '3.9'

services:
  app:
    image: gymkeeper-app:latest
    ports:
      - "8080:8080"
    container_name: gymkeeper
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=gymkeeper-db
    container_name: gymkeeper-postgres-db

volumes:
  postgres-data: